# Generated by Django 2.0.2 on 2018-03-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180316_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dilike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
