# Generated by Django 2.0.2 on 2018-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180317_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book.jpg', upload_to='templates/catalog/img'),
        ),
    ]
