# Generated by Django 2.0.2 on 2018-03-25 17:30

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=catalog.models.Book.get_image_name),
        ),
    ]
