# Generated by Django 2.0.2 on 2018-03-25 18:00

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180325_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=catalog.models.Book.get_image_name),
        ),
    ]
