# Generated by Django 2.0.2 on 2018-03-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1000)),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Branch')),
            ],
        ),
    ]
