# Generated by Django 2.0.2 on 2018-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
